### ISSUE TITLE
Error in Babel compiling

### ISSUE THREAD

**Issue by Tin-Nguyen** [LucianoGanga/simple-headless-chrome#30]
I got the issue when running the package with babel
```
/WORK_SPACE/test/node_modules/simple-headless-chrome/lib/browser.js:22
const { sleep } = require('./util')
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/WORK_SPACE/test/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/WORK_SPACE/test/node_modules/simple-headless-chrome/index.js:1:18)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/WORK_SPACE/test/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

Please give me an advise to fix it.

**Comment by Tin-Nguyen** [comment]
I have resolve the issue, it's my fault. Close the issue
