### ISSUE TITLE
Sample example not working

### ISSUE THREAD

**Issue by guidanz** [LucianoGanga/simple-headless-chrome#43]
I have node version 4.2.x and I have installed the npm.

I'm trying out the sample example given below,
I have saved the file as index.js
`const HeadlessChrome = require('simple-headless-chrome')
const browser = new HeadlessChrome({
        headless: true,
        launchChrome: true ,
        chrome: {
            host: 'localhost',
            port: 9222, // Chrome Docker default port
            remote: true,
        },
        browserlog: true
    });
    this.browser = browser.init().then(function (data) {
        return browser;
    }, function (err) {
        console.log(err)
    })
    console.log(this.browser.goTo); 
`

I execute as **node index.js**
and I get the following error,
function launch(opts = {}) {
                     ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/guidanz-kavi/Documents/nodeApplication/skedler/node_modules/chrome-launcher/index.js:6:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

Please guide me resolve this error.
Thanks.

**Comment by gr2m** [comment]
> `function launch(opts = {}) {`

node 4 does not support default values. Can you try node 6.4 or above?

**Comment by LucianoGanga** [comment]
Can you try again with the new version? 

Also, try cloning the repository and running "npm run test" in your local machine to see if the tests pass. 

Thanks!
Lucho

**Comment by LucianoGanga** [comment]
@gr2m shouldn't babel remove the default values declarations?

**Comment by guidanz** [comment]
Upgrading node version resolved the error
