### ISSUE TITLE
Error using sample code in readme

### ISSUE THREAD

**Issue by bobbysteel** [LucianoGanga/simple-headless-chrome#5]
Any ideas?

await browser.init()
      ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by LucianoGanga** [comment]
Hi! Each method of the module returns a promise; In the readme case, if you want to make use of "await" in each promise, you have to put your code inside an async fn (like in this case: https://github.com/LucianoGanga/simple-headless-chrome/issues/2#issuecomment-305537661) 

I hope it helps! 

Cheers, 
Luciano

**Comment by bobbysteel** [comment]
Thanks for the fast response! I've pared it back to just a few lines and that example throws an error too.
await function navigateGoogle () {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Could you suggest a quick code snippet so i can test a simple fetch HTML to get me started? Really appreciate your work and help!

**Comment by bobbysteel** [comment]
Just using browser.goto gives this error 

  async init () {
        ^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/robk/node/node_modules/simple-headless-chrome/index.js:1:80)
    at Module._compile (module.js:570:32)


Feels like I've got something configured wrong?

**Comment by LucianoGanga** [comment]
What Node version are you using? 

"async" functions are available since node version 7.10.

**Comment by bobbysteel** [comment]
ah crap. just upgraded to 8.10 now. that seems better in that it executes now and returns. is there an easy way to turn on some sort of logging for the session? i've tried headless: true but it doesn't show anything.
