### ISSUE TITLE
chrome-launcher not stating

### ISSUE THREAD

**Issue by webciter** [LucianoGanga/simple-headless-chrome#82]
/home/developer/node_modules/chrome-launcher/chrome-launcher.js:31
function launch(opts = {}) {
                     ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/developer/node_modules/chrome-launcher/index.js:6:10)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by LucianoGanga** [comment]
Hello @webciter !
How are you starting the module? How did you install it? How are you using it? 
I need more information to help you.

Thanks!
Lucho

**Comment by webciter** [comment]
the issue is now sorted i installed node that was built into Ubuntu 16.04 which was an old version so i downloaded nodejs from there servers and copied the binary to /usr/bin as node2, now i run it as node2 then it works, iv now got the browser functioning.
