### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by pavei** [LucianoGanga/simple-headless-chrome#88]
Hello,

I'm getting one error, but i dont know what is the cause.. :

````
Error: [Headless Chrome] Timeout after 60000 ms
Error: [Headless Chrome] Timeout after 60000 ms
at Timeout._onTimeout (/app/node_modules/simple-headless-chrome/build/util.js:48:17)
at ontimeout (timers.js:488:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:283:5)
````

**Comment by Tin-Nguyen** [comment]
You can set the timeout (ms) when call `goTo` function
